before:
  hooks:
    - go mod download
builds:
- env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  goos:
    - darwin
    - windows
    - linux
  goarch:
    - amd64
    - arm64
  ldflags: -X github.com/kenXengineering/aws-sso-creds/pkg/version.Version={{.Version}}
  binary: aws-sso-creds
  main: ./cmd/aws-sso-creds/main.go
archives:
- name_template: "{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"
  format_overrides:
    - goos: windows
      format: zip
snapshot:
  name_template: "{{ .Tag }}-SNAPSHOT"
changelog:
  skip: true
release:
  prerelease: auto
brews:
  - name: aws-sso-creds
    repository:
      owner: kenXengineering
      name: homebrew-tap
    commit_author:
      name: GitHub Actions
      email: ken@kenxengineering.com
    folder: Formula
    homepage: "https://google.com"
    description: "Helper utility to get temporary credentials from AWS SSO."
scoops:
  - url_template: "http://github.com/kenXengineering/aws-sso-creds/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    repository:
      owner: kenXengineering
      name: scoop-bucket
      branch: main
    commit_author:
      name: KenX
      email: ken@kenxengineering.com
    commit_msg_template: "Scoop update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: "https://google.com/"
    description: "Helper utility to get temporary credentials from AWS SSO."
